#!/usr/bin/env python3
"""A ledger that groups kernel-panic reports into distinct bugs and tracks each
bug's investigation from first crash to filed report.

The problem this solves: a fuzzer produces many panic files, one root-cause bug
produces several of them (it can crash as an out-of-bounds read one run and a
null-write the next), and the raw backtrace signature both over-splits those and
mislabels coverage-relocated faults. So panics pile up and blur together.

crash_fingerprint.analyze() reduces each panic to a bug_key --
"<driver>:<method>:<fault-class>" -- that groups a bug's manifestations while
keeping different bugs apart. This tool routes panics by that key:

  - registry.json is the machine-readable source of truth: bug_key -> {id,
    status, the crashes seen, report status, dossier path}.
  - bugs/BUG-000N-<slug>.md is a human dossier per bug, created once from a
    template and freely editable; routing only rewrites the delimited
    auto-evidence block inside it, never your prose.
  - INDEX.md is regenerated from the registry as an at-a-glance board.

Usage:
  bug_registry.py route  <panic>...   # analyze + file each panic under its bug
  bug_registry.py list                # print the board
  bug_registry.py index               # just regenerate INDEX.md
  bug_registry.py show   <BUG-id|key> # print one bug's registry record
  bug_registry.py attribute --sig S --culprit F   # record a verified reproducer

--bugs sets the registry dir (default <tree>/campaigns/bugs, the inventory the
campaign driver writes to), --symbols the driver symbol maps (passed through to
analyze).
"""

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import crash_fingerprint as cf  # noqa: E402
from tablefmt import render as _render_table  # noqa: E402
from fsutil import hardlink_or_copy  # noqa: E402
import timefmt  # noqa: E402

# Investigation gates, in order. A dossier advances through these; the registry
# records the current one so a bug is never "where was I?" again.
STATUSES = ("new", "investigating", "poc", "reported", "fixed", "dup")

# How a panic came to be. "fuzz" is a genuine find; "triage" is one the minimizer
# caused ON PURPOSE while re-running a known-crashing subset. Both belong in the
# evidence log -- a triage panic still proves the bug -- but only fuzz-origin
# crashes may be counted as sightings, because crash frequency is a
# prioritization signal and investigating a bug must not inflate its own rank.
ORIGINS = ("fuzz", "triage")
# Rows written before the field existed: they predate any triage routing, so
# reading them as fuzz-origin is correct rather than merely convenient.
DEFAULT_ORIGIN = "fuzz"

# The registry lives beside the campaign state, not in the cwd: every writer
# (the campaign driver, triage, a human) must land in the same inventory or the
# dedup by bug_key silently stops working.
TREE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_BUGS_DIR = os.path.join(TREE_ROOT, "campaigns", "bugs")

AUTO_START = "<!-- AUTO-EVIDENCE:START -- regenerated by bug_registry; do not edit inside -->"
AUTO_END = "<!-- AUTO-EVIDENCE:END -->"


# --- registry io ------------------------------------------------------------
def registry_path(bugs_dir):
    return os.path.join(bugs_dir, "registry.json")


def load_registry(bugs_dir, must_exist=False):
    """Read the registry. must_exist=True is for the read-only commands: a
    missing registry there means the caller is pointed at the wrong directory,
    and answering "no bugs" would let a typo read as good news."""
    path = registry_path(bugs_dir)
    if must_exist and not os.path.exists(path):
        print("no registry at %s\n"
              "  (pass --bugs <dir>; the campaign inventory is %s)"
              % (path, DEFAULT_BUGS_DIR), file=sys.stderr)
        sys.exit(2)
    try:
        with open(path) as f:
            data = json.load(f)
    except (OSError, ValueError):
        return {"counter": 0, "bugs": {}}
    data.setdefault("counter", 0)
    data.setdefault("bugs", {})
    return data


def save_registry(bugs_dir, reg):
    os.makedirs(bugs_dir, exist_ok=True)
    path = registry_path(bugs_dir)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(reg, f, indent=2)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def slugify(text):
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return s or "bug"


# --- dossier ----------------------------------------------------------------
def dossier_template(rec):
    """The one-time scaffold for a bug dossier. Human sections are left for you
    to fill; the auto-evidence block is owned by the tool."""
    return """# {id} -- {key}

- **status:** {status}
- **method:** {method}
- **fault class:** {fault_class}
- **selector:** _tbd_
- **report status:** {report_status}

## Summary

_What the bug is, in one paragraph._

## Root cause

_The faulting operation and why it is wrong (offsets, the missing bound, etc.)._

## Reproduce

_Minimal syz-ring-repro case / standalone PoC; the selector and inputs._

## Impact

_Read vs write, leak channel, DoS, entitlement required._

## Apple report

_Summary / Steps / Expected / Actual, and the Feedback ID once filed._

{auto_start}
{auto_end}
""".format(
        id=rec["id"], key=rec["bug_key"], status=rec["status"],
        method=rec.get("method") or "?", fault_class=rec["fault_class"],
        report_status=rec["report_status"],
        auto_start=AUTO_START, auto_end=AUTO_END)


def render_reproducer(rec):
    """The auto-owned reproducer block: what minimization proved, if anything.

    This is the payload of the whole pipeline -- the smallest call sequence known
    to reproduce -- so it leads the dossier rather than hiding at the bottom of
    an evidence table. Absent until triage attributes one."""
    rp = rec.get("reproducer")
    if not rp:
        return ("## Reproducer\n\n"
                "_None yet. Triage has not produced a minimized culprit for this "
                "bug._")
    lines = ["## Reproducer", ""]
    lines.append("- **verified**: %s" % ("yes -- reproduced standalone"
                                         if rp.get("verified")
                                         else "NO -- needs accumulated state, see caveat below"))
    if rp.get("selectors"):
        lines.append("- **selector(s)**: %s"
                     % ", ".join("`%s`" % s for s in rp["selectors"]))
    if rp.get("calls") is not None:
        lines.append("- **length**: %d call(s)" % rp["calls"])
    if rp.get("path"):
        lines.append("- **file**: `%s`" % rp["path"])
    if rp.get("job"):
        lines.append("- **triage job**: `%s`" % rp["job"])
    if rp.get("at"):
        lines.append("- **attributed**: %s" % timefmt.fmt(rp["at"]))
    if not rp.get("verified"):
        lines += ["",
                  "> The minimizer could not make this crash on its own. It fired "
                  "during the search but not on isolated re-check, so it depends "
                  "on state an earlier program left behind. Treat the sequence as "
                  "a lead, not a proof."]
    if rp.get("body"):
        lines += ["", "```", _elide(rp["body"]), "```",
                  "", "_Long buffer literals are elided above; the file at the "
                  "path is the exact input._"]
    return "\n".join(lines)


# A syzkaller call carries its buffers as one hex literal, routinely 4KB on a
# single line. Verbatim that makes the dossier unreadable in any viewer, so the
# rendering elides the middle -- the file on disk stays the source of truth.
_ELIDE_AT = 160


def _elide(body, width=_ELIDE_AT):
    out = []
    for ln in body.rstrip().splitlines():
        if len(ln) > width:
            keep = width // 2 - 12
            ln = "%s ...[%d chars]... %s" % (ln[:keep], len(ln) - 2 * keep, ln[-keep:])
        out.append(ln)
    return "\n".join(out)


def render_evidence(rec):
    """The auto-owned evidence block: the crash manifestations seen for this
    bug, newest last, each with the facts that identify it."""
    n_fuzz = sum(1 for c in rec["crashes"] if crash_origin(c) == "fuzz")
    n_tri = len(rec["crashes"]) - n_fuzz
    lines = [render_reproducer(rec), "", "## Evidence log", "",
             "| when | origin | report | fault | far | culprit | pc | pgz | sig |",
             "|------|--------|--------|-------|-----|---------|----|-----|-----|"]
    for c in rec["crashes"]:
        lines.append("| %s | %s | `%s` | %s | %s | %s | %s | %s | `%s` |" % (
            timefmt.fmt(c.get("first_seen"), default="?"), crash_origin(c),
            c["report"], c["fault_class"],
            c.get("far") or "-", c.get("culprit") or "-", c.get("pc") or "-",
            c.get("pgz") or "-", c.get("signature") or "-"))
    lines.append("")
    tail = ("" if not n_tri else
            " (%d self-inflicted by minimization, not counted as sightings)" % n_tri)
    lines.append("_%d crash(es) grouped under this bug%s._" % (n_fuzz, tail))
    return "\n".join(lines)


def write_dossier(bugs_dir, rec):
    """Create the dossier if absent, then rewrite only its auto-evidence block."""
    path = os.path.join(bugs_dir, rec["dossier"])
    if not os.path.exists(path):
        with open(path, "w") as f:
            f.write(dossier_template(rec))
    with open(path) as f:
        body = f.read()
    block = "%s\n%s\n%s" % (AUTO_START, render_evidence(rec), AUTO_END)
    if AUTO_START in body and AUTO_END in body:
        body = re.sub(re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END),
                      lambda _: block, body, count=1, flags=re.S)
    else:  # dossier was edited to drop the markers; append a fresh block.
        body = body.rstrip() + "\n\n" + block + "\n"
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(body)
    os.replace(tmp, path)


# --- routing ----------------------------------------------------------------
def crash_record(a, campaign=None, config=None, origin=DEFAULT_ORIGIN):
    """The per-crash row we keep: the discriminators, de-slid so they mean the
    same thing across reboots, plus which run produced it.

    Provenance is what makes ONE deduped inventory answer per-campaign questions
    ("what did this run find?") without splitting the registry -- splitting would
    restart the counter per campaign, so two unrelated bugs would both be
    BUG-0001 and a later merge would have to re-dedup by bug_key anyway."""
    culprit = a["culprit_module"] or "?"
    if a["culprit_off"] is not None:
        culprit += "+0x%x" % a["culprit_off"]
    if a["culprit_func"]:
        culprit += " (%s%s)" % (a["culprit_func"],
                                " inferred" if a.get("culprit_func_confidence") == "inferred" else "")
    return {
        "report": os.path.basename(a["report"]),
        "first_seen": cf.now_iso(),
        "fault_class": a["fault_class"],
        "far": ("0x%x" % a["far"]) if isinstance(a["far"], int) else None,
        "culprit": culprit,
        "pc": a["pc_site"] + (" [instr]" if a["pc_instrumented"] else "") if a["pc_site"] else None,
        "pgz": a["pgz_verdict"],
        "signature": a["signature"],
        "campaign": campaign,
        "config": config,
        "origin": origin,
    }


def crash_origin(c):
    return c.get("origin") or DEFAULT_ORIGIN


def bug_reports_dir(bugs_dir, rec):
    return os.path.join(bugs_dir, rec["id"], "reports")


def keep_report(bugs_dir, rec, report_path):
    """Link a panic report under the bug that cites it. Best effort: failing to
    hold a copy must never stop the crash from being filed."""
    try:
        d = bug_reports_dir(bugs_dir, rec)
        os.makedirs(d, exist_ok=True)
        hardlink_or_copy(report_path, os.path.join(d, os.path.basename(report_path)))
    except OSError:
        pass


def route_one(reg, bugs_dir, a, campaign=None, config=None, origin=DEFAULT_ORIGIN):
    """File one analyzed panic under its bug_key, creating the bug if new.
    Returns (bug_id, status, is_new_bug, is_new_crash)."""
    key = a["bug_key"]
    rec = reg["bugs"].get(key)
    is_new_bug = rec is None
    if is_new_bug:
        reg["counter"] += 1
        bug_id = "BUG-%04d" % reg["counter"]
        rec = {
            "id": bug_id,
            "bug_key": key,
            "status": "new",
            "method": a["culprit_func"],
            "fault_class": a["fault_class"],
            "report_status": "not-filed",
            "first_seen": cf.now_iso(),
            "crashes": [],
            "dossier": "%s-%s.md" % (bug_id, slugify(
                "%s-%s" % (a["culprit_func"] or a["culprit_module"] or "bug",
                           a["fault_class"]))),
        }
        reg["bugs"][key] = rec
    # Dedup crashes by report basename so re-routing is idempotent.
    name = os.path.basename(a["report"])
    existing = next((c for c in rec["crashes"] if c["report"] == name), None)
    is_new_crash = existing is None
    if is_new_crash:
        rec["crashes"].append(crash_record(a, campaign, config, origin))
    elif "origin" not in existing and origin != DEFAULT_ORIGIN:
        # Backfill only: a row written before origin existed defaults to "fuzz",
        # so re-routing a known triage panic with --origin triage corrects it.
        # An explicit origin is never overwritten -- that would let a re-route
        # silently relabel a genuine find.
        existing["origin"] = origin
    # Hold the evidence, not just its filename. The registry stored a basename
    # pointing into /Library/Logs/DiagnosticReports -- a directory macOS rotates
    # on its own -- so a dossier's oldest citations rot without anyone deleting
    # anything. A hardlink costs no blocks and cannot be rotated away.
    keep_report(bugs_dir, rec, a["report"])
    rec["last_seen"] = cf.now_iso()
    # Backfill a method name if the symbol map has since learned it.
    if a["culprit_func"] and not rec.get("method"):
        rec["method"] = a["culprit_func"]
    write_dossier(bugs_dir, rec)
    return rec["id"], rec["status"], is_new_bug, is_new_crash


# --- INDEX ------------------------------------------------------------------
def write_index(bugs_dir, reg):
    rows = sorted(reg["bugs"].values(), key=lambda r: r["id"])
    n_fuzz = sum(1 for r in rows for c in r["crashes"] if crash_origin(c) == "fuzz")
    n_tri = sum(len(r["crashes"]) for r in rows) - n_fuzz
    lines = ["# Bug registry", "",
             "%d bug(s), %d crash(es) found by fuzzing%s." % (
                 len(rows), n_fuzz,
                 "" if not n_tri else
                 " (+%d caused by minimization while investigating)" % n_tri), "",
             "| id | status | report | repro | sig | bug_key | crashes | dossier |",
             "|----|--------|--------|-------|-----|---------|---------|---------|"]
    for r in rows:
        sigs = bug_signatures(r)
        sig = (sigs[0] + (" +%d" % (len(sigs) - 1) if len(sigs) > 1 else "")
               ) if sigs else "-"
        rp = r.get("reproducer") or {}
        repro = "-" if not rp else ("verified" if rp.get("verified") else "unverified")
        mine = sum(1 for c in r["crashes"] if crash_origin(c) == "fuzz")
        tri = len(r["crashes"]) - mine
        lines.append("| %s | %s | %s | %s | `%s` | `%s` | %d%s | [%s](%s) |" % (
            r["id"], r["status"], r["report_status"], repro, sig, r["bug_key"],
            mine, " (+%d)" % tri if tri else "", r["dossier"], r["dossier"]))
    lines.append("")
    path = os.path.join(bugs_dir, "INDEX.md")
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(lines))
    os.replace(tmp, path)


# --- commands ---------------------------------------------------------------
def cmd_route(args):
    reg = load_registry(args.bugs)
    symbols = cf.load_symbols(args.symbols)
    os.makedirs(args.bugs, exist_ok=True)
    for path in args.report:
        try:
            a = cf.analyze(path, symbols)
        except Exception as e:  # noqa: BLE001
            print("%s\n  error: %s" % (path, e), file=sys.stderr)
            continue
        origin = getattr(args, "origin", DEFAULT_ORIGIN)
        bug_id, status, new_bug, new_crash = route_one(
            reg, args.bugs, a, getattr(args, "campaign", None),
            getattr(args, "config", None), origin)
        tag = "NEW BUG " if new_bug else ("new crash" if new_crash else "dup      ")
        print("%s  %s [%s]  %s%s" % (tag, bug_id, status, a["bug_key"],
                                     "  (triage-origin)" if origin == "triage" else ""))
    save_registry(args.bugs, reg)
    write_index(args.bugs, reg)


def cmd_index(args):
    reg = load_registry(args.bugs, must_exist=True)
    write_index(args.bugs, reg)
    print("wrote %s" % os.path.join(args.bugs, "INDEX.md"))


def _from_campaign(rec, campaign):
    return any(c.get("campaign") == campaign for c in rec.get("crashes", []))


def bug_signatures(rec):
    """The distinct crash signatures filed under this bug, first seen first.

    Normally one. More than one means the fingerprint is splitting what bug_key
    considers a single bug -- worth knowing, so the listing shows the count."""
    out = []
    for c in rec["crashes"]:
        sig = c.get("signature")
        if sig and sig not in out:
            out.append(sig)
    return out


def _tabulate(rows, headers, gap=2):
    """Print rows in columns sized to their contents (see tablefmt)."""
    for ln in _render_table(rows, headers, gap):
        print(ln)


def cmd_list(args):
    reg = load_registry(args.bugs, must_exist=True)
    rows = sorted(reg["bugs"].values(), key=lambda r: r["id"])
    want = getattr(args, "campaign", None)
    if want:
        rows = [r for r in rows if _from_campaign(r, want)]
    if not rows:
        print("(no bugs registered under %s%s)"
              % (args.bugs, " for campaign %s" % want if want else ""))
        return
    out = []
    for r in rows:
        mine = [c for c in r["crashes"] if not want or c.get("campaign") == want]
        n_fuzz = sum(1 for c in mine if crash_origin(c) == "fuzz")
        n_tri = len(mine) - n_fuzz
        # Sightings and self-inflicted panics are different facts, so they get
        # different shapes: "3" is three finds, "3 (+4)" is three finds and four
        # panics minimization caused while investigating them.
        seen = "%d%s" % (n_fuzz, " (+%d)" % n_tri if n_tri else "")
        sigs = bug_signatures(r)
        sig = (sigs[0] + (" +%d" % (len(sigs) - 1) if len(sigs) > 1 else "")
               ) if sigs else "-"
        rp = r.get("reproducer") or {}
        repro = "-" if not rp else ("verified" if rp.get("verified") else "unverified")
        out.append((r["id"], r["status"], r["report_status"], seen, repro,
                    sig, r["bug_key"]))
    _tabulate(out, ("ID", "STATUS", "REPORT", "SEEN", "REPRO", "SIG", "BUG KEY"))


def find_bug(reg, which=None, sig=None):
    """Locate a bug by id, bug_key, or any crash signature filed under it.

    Signature lookup is what lets the campaign hand off: quarantine and triage
    both speak signatures, and the registry is the only component keyed by
    bug_key, so without this there is no join between them."""
    for r in reg["bugs"].values():
        if which and which in (r["id"], r["bug_key"]):
            return r
    if sig:
        for r in sorted(reg["bugs"].values(), key=lambda x: x["id"]):
            if sig in bug_signatures(r):
                return r
    return None


def cmd_attribute(args):
    """Record the minimized reproducer triage produced for a bug.

    Without this the pipeline's actual output -- the smallest crashing sequence,
    and which selector it blames -- lives only in the quarantine state and a .syz
    file under the triage job, while the dossier that gets turned into a vendor
    report still says method: None."""
    reg = load_registry(args.bugs, must_exist=True)
    rec = find_bug(reg, getattr(args, "which", None), args.sig)
    if rec is None:
        print("no bug matches %s" % (args.which or "signature " + str(args.sig)),
              file=sys.stderr)
        sys.exit(1)
    body, ncalls = None, None
    if args.culprit:
        try:
            with open(args.culprit) as f:
                body = f.read()
            ncalls = sum(1 for ln in body.splitlines() if ln.strip()
                         and not ln.lstrip().startswith("#"))
        except OSError as e:
            print("cannot read culprit %s: %s" % (args.culprit, e), file=sys.stderr)
            sys.exit(1)
    selectors = [s for s in (args.selector or []) if s]
    prev = rec.get("reproducer") or {}
    # A verified reproducer is strictly better evidence than an unverified one,
    # so never let a later unverified attribution overwrite a proven sequence.
    if prev.get("verified") and not args.verified:
        print("%s already has a verified reproducer; keeping it" % rec["id"])
        return
    rec["reproducer"] = {
        "path": os.path.abspath(args.culprit) if args.culprit else prev.get("path"),
        "body": body if body is not None else prev.get("body"),
        "calls": ncalls if ncalls is not None else prev.get("calls"),
        "selectors": selectors or prev.get("selectors") or [],
        "verified": bool(args.verified),
        "job": args.job or prev.get("job"),
        "signature": args.sig or prev.get("signature"),
        "at": cf.now_iso(),
    }
    # The selector IS the method for an IOKit external method, and the symbol
    # map usually cannot supply it. Backfill so the dossier stops saying "?".
    if selectors and not rec.get("method"):
        rec["method"] = selectors[0]
    write_dossier(args.bugs, rec)
    save_registry(args.bugs, reg)
    write_index(args.bugs, reg)
    print("%s: reproducer %s (%s call(s), %s)"
          % (rec["id"], "verified" if args.verified else "UNVERIFIED",
             rec["reproducer"]["calls"] if rec["reproducer"]["calls"] is not None else "?",
             ", ".join(selectors) or "no selector"))


def cmd_show(args):
    reg = load_registry(args.bugs, must_exist=True)
    rec = find_bug(reg, args.which, args.which)
    if rec is not None:
        json.dump(rec, sys.stdout, indent=2)
        print()
        return
    print("not found: %s" % args.which, file=sys.stderr)
    sys.exit(1)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bugs", default=DEFAULT_BUGS_DIR,
                    help="registry dir (default %s)" % DEFAULT_BUGS_DIR)
    ap.add_argument("--symbols",
                    default=os.path.join(os.path.dirname(__file__), "symbols"),
                    help="dir of per-driver symbol maps")
    sub = ap.add_subparsers(dest="cmd")

    pr = sub.add_parser("route", help="analyze + file panic(s) under their bug")
    pr.add_argument("report", nargs="+")
    pr.add_argument("--campaign", help="campaign that produced these panics (provenance)")
    pr.add_argument("--config", help="manager config that produced them (provenance)")
    pr.add_argument("--origin", choices=ORIGINS, default=DEFAULT_ORIGIN,
                    help="'triage' for panics the minimizer caused on purpose; "
                         "they are filed as evidence but not counted as sightings")
    pr.set_defaults(func=cmd_route)

    pa = sub.add_parser("attribute", help="record a minimized reproducer for a bug")
    pa.add_argument("--sig", help="crash signature identifying the bug")
    pa.add_argument("--which", help="BUG-id or bug_key (alternative to --sig)")
    pa.add_argument("--culprit", help="path to the minimized .syz reproducer")
    pa.add_argument("--selector", action="append",
                    help="syscall the reproducer blames (repeatable)")
    pa.add_argument("--job", help="triage job that produced it")
    pa.add_argument("--verified", action="store_true",
                    help="the reproducer crashed standalone on isolated re-check")
    pa.set_defaults(func=cmd_attribute)

    sub.add_parser("index", help="regenerate INDEX.md").set_defaults(func=cmd_index)
    pl = sub.add_parser("list", help="print the board")
    pl.add_argument("--campaign", help="only bugs with at least one crash from this campaign")
    pl.set_defaults(func=cmd_list)

    psh = sub.add_parser("show", help="print one bug's registry record")
    psh.add_argument("which", help="BUG-id or bug_key")
    psh.set_defaults(func=cmd_show)

    args = ap.parse_args()
    if not getattr(args, "func", None):
        ap.print_help()
        sys.exit(2)
    args.func(args)


if __name__ == "__main__":
    main()
